from pathlib import Path

PROJ_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJ_ROOT / "data"

UvA_NEMO_SMILE_DATABASE_DIR = DATA_DIR / "UvA-NEMO_SMILE_DATABASE"
UvA_NEMO_SMILE_DETAILS = (
    UvA_NEMO_SMILE_DATABASE_DIR / "UvA-NEMO_Smile_Database_File_Details.txt"
)
UvA_NEMO_SMILE_VIDEOS_DIR = UvA_NEMO_SMILE_DATABASE_DIR / "videos"

PREPROCESSED_DATA_DIR = DATA_DIR / "preprocessed_UvA-NEMO_SMILE_DATABASE"
PREPROCESSED_FRAMES_DIR = PREPROCESSED_DATA_DIR / "frames"
PREPROCESSED_FACELANDMARKS_DIR = PREPROCESSED_DATA_DIR / "facelandmarks"

ORIGINAL_DATA = DATA_DIR / "original_data"
ORIGINAL_FRAMES_DIR = ORIGINAL_DATA / "frames"
ORIGINAL_FACELANDMARKS_DIR = ORIGINAL_DATA / "facelandmarks"
