from pathlib import Path

PROJ_ROOT = Path(__file__).resolve().parents[1]

LOGS_DIR = PROJ_ROOT / "logs"
DATA_DIR = PROJ_ROOT / "data"

UvA_NEMO_SMILE_DATABASE_DIR = DATA_DIR / "UvA-NEMO_SMILE_DATABASE"
UvA_NEMO_SMILE_DETAILS = UvA_NEMO_SMILE_DATABASE_DIR / "UvA-NEMO_Smile_Database_File_Details.txt"
UvA_NEMO_SMILE_VIDEOS_DIR = UvA_NEMO_SMILE_DATABASE_DIR / "videos"

PREPROCESSED_DATA_DIR = DATA_DIR / "preprocessed_UvA-NEMO_SMILE_DATABASE"
PREPROCESSED_FRAMES_DIR = PREPROCESSED_DATA_DIR / "frames"
PREPROCESSED_FACELANDMARKS_DIR = PREPROCESSED_DATA_DIR / "facelandmarks"
PREPROCESSED_SMILE_PHASES_DIR = PREPROCESSED_DATA_DIR / "smile_phases"

LIP_FEATURES_DIR = PREPROCESSED_DATA_DIR / "lip_features"
ALL_LIP_FEATURES_CSV = PREPROCESSED_DATA_DIR / "all_lip_features.csv"

EYES_FEATURES_DIR = PREPROCESSED_DATA_DIR / "eyes_features"
ALL_EYES_FEATURES_CSV = PREPROCESSED_DATA_DIR / "all_eyes_features.csv"

CHEEKS_FEATURES_DIR = PREPROCESSED_DATA_DIR / "cheeks_features"
ALL_CHEEKS_FEATURES_CSV = PREPROCESSED_DATA_DIR / "all_cheeks_features.csv"

ORIGINAL_DATA = DATA_DIR / "original_data"
ORIGINAL_FRAMES_DIR = ORIGINAL_DATA / "frames"
ORIGINAL_FACELANDMARKS_DIR = ORIGINAL_DATA / "facelandmarks"

CHECKPOINT_FILE_PATH = PREPROCESSED_DATA_DIR / "processed_files.csv"

RUNS_DIR = PROJ_ROOT / "runs"
LIPS_RUNS_DIR = RUNS_DIR / "lips_runs"
EYES_RUNS_DIR = RUNS_DIR / "eyes_runs"
CHEEKS_RUNS_DIR = RUNS_DIR / "cheek_runs"

EYE_RELATIVE_LEFT = 0.35
EYE_RELATIVE_TOP = 0.35
EYE_RELATIVE_SIZE = (EYE_RELATIVE_LEFT, EYE_RELATIVE_TOP)

DESIRED_FRAME_WIDTH = 256
DESIRED_FRAME_HEIGHT = 256
DESIRED_FRAME_SIZE = (DESIRED_FRAME_WIDTH, DESIRED_FRAME_HEIGHT)
